apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ .Values.service.name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: JAVA_OPTS
          value: -Xmx{{ .Values.javaOpts.xmx }} -Xms{{ .Values.javaOpts.xms }} {{ .Values.javaOpts.other}}
        - name: SPRING_RABBITMQ_HOST
        {{- if .Values.global.rabbitmq.host.value }}
          value: {{ .Values.global.rabbitmq.host.value }}
        {{ else }}
          value: {{ .Release.Name }}-rabbitmq
        {{ end }}
        - name: SPRING_RABBITMQ_USERNAME
          value: {{ .Values.global.rabbitmq.username.value }}
        - name: SPRING_RABBITMQ_PASSWORD
          value: {{ .Values.global.rabbitmq.password.value }}
#        - name: ACT_RB_DB_URI
#        {{- if .Values.db.uri }}
#          value: {{ .Values.db.uri }}
#        {{ else }}
#          value: jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/postgres
#        {{ end }}
#        - name: ACT_RB_DB_USER
#          value: {{ default "postgres" .Values.db.user }}
#        - name: ACT_RB_DB_PASS
#        {{- if .Values.db.pass }}
#          value: {{ .Values.db.pass }}
#        {{ else }}
#          valueFrom:
#            secretKeyRef:
#              name: {{ .Release.Name }}-postgresql
#              key: postgres-password
#        {{ end }}
#        - name: ACT_RB_DB_PLATFORM
#          value: {{ default "org.hibernate.dialect.PostgreSQLDialect" .Values.db.platform }}
        - name: CAMPAIGN_TOPIC
          value: {{ default "activiti" .Values.global.campaign }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probePath }}
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probePath }}
            port: {{ .Values.service.internalPort }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      serviceAccountName: {{ .Chart.Name }}
